/**
 * Data model (CODING_PLAN §2.1).
 *
 * Same semantics as the template. scope picks the column (General or Individual), source
 * picks the section inside that column (Internal or External).
 */

/** Current document format version. Bump it when the structure changes; a higher version is rejected outright. */
export const SCHEMA_VERSION = 1;

/** Scope: whether the entry goes in the General or Individual column. */
export type Scope = 'general' | 'individual';
/** Source: whether the entry goes in that column's Internal or External section. */
export type Source = 'internal' | 'external';

/** The four cells, shaped like `general-internal`. */
export type CellId = `${Scope}-${Source}`;

/** The author of an osu! post, used for attribution. */
export interface SourceAuthor {
  /** osu! username. */
  username: string;
  /** osu! user id. Omitted when we only got the username and couldn't resolve the numeric id. */
  id?: number;
}

/** Context for jumping back to the original beatmap discussion; fill in whatever we can get. */
export interface EntryMeta {
  /** Beatmapset id. */
  beatmapsetId?: number;
  /** The specific difficulty id (/discussion/<beatmapId>/…). generalAll and the like don't have one. */
  beatmapId?: number;
  /** Game mode, like 'mania' / 'osu' / 'taiko' / 'catch'. */
  mode?: string;
}

export interface ChecklistEntry {
  /** Entry id, generated by randomUUID(). */
  id: string;
  /** Which column it goes in. */
  scope: Scope;
  /** Which section of that column it goes in. */
  source: Source;
  /** Summary. Keep the original wording where possible, or a one-line paraphrase. */
  summary: string;
  /** Example links. The first one is usually the original post's permalink. */
  links: string[];
  /**
   * The author resolved for each link, keyed by the raw URL in links.
   *
   * Keyed by URL rather than by index because links get added, removed and edited, and a
   * plain index would then point the author at the neighbouring link. Editing one link
   * also touches only its own key, and a key orphaned by a removed link can't be looked
   * up at render time anyway, so it just reads as absent.
   */
  linkAuthors?: Record<string, SourceAuthor>;
  /** A note the user added. The field isn't stored when there is none. */
  note?: string;
  /** The author of the source post. */
  sourceAuthor?: SourceAuthor;
  /** The context used to jump back to the original discussion. */
  meta?: EntryMeta;
  /** Creation time, in milliseconds since the epoch. */
  createdAt: number;
  /** Last modified time, in milliseconds since the epoch. Used to compare newness during sync. */
  updatedAt: number;
}

export interface ChecklistDoc {
  /** Document format version; written as the current SCHEMA_VERSION. */
  schemaVersion: number;
  /** Millisecond timestamp for the whole document; used for sync and conflict decisions. */
  updatedAt: number;
  /**
   * Generated once when the document is first created, then kept from then on. `d-`
   * prefixed, to tell it apart from entry ids.
   */
  deviceId: string;
  // There used to be a lastSyncedAt here. It was dropped: it duplicates lastSyncAt in the
  // sync state, and keeping it in the document made every sync change the content, so
  // "is the remote the same as local" always came out different and everything got
  // uploaded again for nothing.
  /** The entries in the four cells. Array order is the manual order within the cell; the index itself isn't stored. */
  cells: Record<CellId, ChecklistEntry[]>;
}

/** Input for adding an entry. id and timestamps are generated by the store, so they aren't given here. */
export interface NewEntryInput {
  /** Which column it goes in; scope + source together decide the target cell, and both are required. */
  scope: Scope;
  /** Which section of that column it goes in. */
  source: Source;
  /** Summary, same as `ChecklistEntry.summary`: the original wording, or a one-line paraphrase. */
  summary: string;
  /** Example links. Omitted means an empty array. */
  links?: string[];
  /** Key = the raw URL in links. */
  linkAuthors?: Record<string, SourceAuthor>;
  /** User note. Omitted means the field isn't stored. */
  note?: string;
  /** The author of the source post. */
  sourceAuthor?: SourceAuthor;
  /** The context used to jump back to the original discussion. */
  meta?: EntryMeta;
}
